

CIFAR10:   # name needs to be matched with dataset class name
  root: E:\python_project\multi-pressure-distillation\datasets
  trainset_sample_ratio: 1.0  # for few shot learning
  seed: 1  # random seed for trainset sample
  download: True
  

CIFAR100:   # name needs to be matched with dataset class name
  root: E:\python_project\multi-pressure-distillation\datasets
  trainset_sample_ratio: 1.0  # for few shot learning
  seed: 1  # random seed for trainset sample
  download: True